version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Building project...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - target/*.jar